"""Domain layer — business types independent of Telegram."""

from domain.dates import (
    MOSCOW_TZ,
    SAMARA_TZ,
    combine_datetime,
    format_date,
    format_time,
    parse_time,
    today,
)
from domain.enums import BookingStatus, CallbackAction, SlotStatus
from domain.exceptions import (
    AlreadyHasBookingError,
    AppError,
    BookingNotFoundError,
    DayClosedError,
    DayNotFoundError,
    DuplicateSlotError,
    InvalidReceiptError,
    NotSubscribedError,
    PaymentNotFoundError,
    PaymentRequiredError,
    PermissionDeniedError,
    SlotNotAvailableError,
    SlotNotFoundError,
    StaleCallbackError,
    UserBlockedError,
    ValidationError,
)

__all__ = [
    "MOSCOW_TZ",
    "SAMARA_TZ",
    "AlreadyHasBookingError",
    "AppError",
    "BookingNotFoundError",
    "BookingStatus",
    "CallbackAction",
    "DayClosedError",
    "DayNotFoundError",
    "DuplicateSlotError",
    "InvalidReceiptError",
    "NotSubscribedError",
    "PaymentNotFoundError",
    "PaymentRequiredError",
    "PermissionDeniedError",
    "SlotNotAvailableError",
    "SlotNotFoundError",
    "SlotStatus",
    "StaleCallbackError",
    "UserBlockedError",
    "ValidationError",
    "combine_datetime",
    "format_date",
    "format_time",
    "parse_time",
    "today",
]
